export const listing = [
    {
    userId: 1,
    entityName: 'Solution Tutors',
    description: 'Weekend class for adult',
    avatar: '',
    coverPhoto: '',
    country: 'Nigeria',
    city: 'mainland',
    state: 'Lagos',
    openingHours: '',
    socialLinks: '',
    entityType: 'tutorial centre',
    docLink: '',
    isValidated: true,
    },
    {
        userId: 2,
        entityName: 'Solution Tutors',
        description: 'Weekend class for adult',
        avatar: '',
        coverPhoto: '',
        country: 'Nigeria',
        city: 'mainland',
        state: 'Lagos',
        openingHours: '',
        socialLinks: String,
        entityType: 'tutorial centre',
        docLink: '',
        isValidated: true,
    },
    {
        userId: 3,
        entityName: 'Solution Tutors',
        description: 'Weekend class for adult',
        avatar: '',
        coverPhoto: '',
        country: 'Nigeria',
        city: 'mainland',
        state: 'Lagos',
        openingHours: '',
        socialLinks: String,
        entityType: 'tutorial centre',
        docLink: '',
        isValidated: true,
    },
    {
        userId: 4,
        entityName: 'Solution Tutors',
        description: 'Weekend class for adult',
        avatar: '',
        coverPhoto: '',
        country: 'Nigeria',
        city: 'mainland',
        state: 'Lagos',
        openingHours: '',
        socialLinks: String,
        entityType: 'tutorial centre',
        docLink: '',
        isValidated: true,
        },
        {
            userId: 5,
            entityName: 'Solution Tutors',
            description: 'Weekend class for adult',
            avatar: '',
            coverPhoto: '',
            country: 'Nigeria',
            city: 'mainland',
            state: 'Lagos',
            openingHours: '',
            socialLinks: String,
            entityType: 'tutorial centre',
            docLink: '',
            isValidated: true,
            }
  ]