import React, { Component } from 'react';

export default class SearchContainer extends Component {

    constructor(props){
        super(props)
        this.state = {

        }
    }

    componentDidMount(){
        this.initPlugin()
    }

    initPlugin(){
        let elems = document.querySelectorAll('#search');
        let instances = M.Autocomplete.init(elems, {
            data: {
            "Apple": null,
            "Microsoft": null,
            "Google": 'https://placehold.it/250x250',
            "Call Centers": null,
            "Wealth Management": null,
            "Small Business Lending": null,
            "Atmel AVR": null,
            "Industrial Ethernet": null,
            "Back Office": null,
            "Political Science": null,
            "Fax": null,
            "Microsoft Word": null,
            "New Media": null,
            "Prenuptial Agreements": null,
            "Citrix XenDesktop": null,
            "Algebra": null,
            "Professional Ethics": null,
            "KDevelop": null,
            "CSPro": null,
            "PFGE": null,
            "Nuclear": null,
            "OLEDB": null,
            "Human Resource Planning": null,
            "FDT": null,
            "Focus Groups": null,
            "Sniffer": null,
            "Vocal": null,
            "Kaizen Leadership": null,
            "WCDMA": null,
            "PyUnit": null,
            "WDF": null,
            "Nuclear": null,
            "Yardi Property Management": null,
            "DOS": null,
            "Slackware": null,
            "Business Transformation": null,
            "TVPaint": null,
            "BDD": null,
            "NPO": null,
            "HR Project Management": null,
            "UK Employment Law": null,
            "QAD": null,
            "Artistic Eye": null,
            "World War II": null,
            "Performance Improvement": null,
            "Tk": null,
            "CMC Regulatory Affairs": null,
            "MDA": null,
            "NLS": null,
            "Glasses": null,
            "Twist": null,
            "Kinematics": null,
            "OnQ": null,
            "Hadoop": null,
            "Homeland Security": null,
            "Power Systems": null,
            "FMEA": null,
            "RPT": null,
            "Unix": null,
            "RPG III": null,
            "Knitting": null,
            "RQM": null,
            "OWA": null,
            "Yachting": null,
            "VDSL": null,
            "Brain Gym": null,
            "SAP PS": null,
            "Vulnerability Scanning": null,
            "Grief Counseling": null,
            "HVAC Controls": null,
            "QINSy": null,
            "Agrochemicals": null,
            "Recombinant DNA": null,
            "NBAP": null,
            "OnQ": null,
            "xPON": null,
            "CCIM": null,
            "IELTS": null,
            "BSS": null,
            "Ukrainian": null,
            "SLA": null,
            "Eaglesoft": null,
            "Event Planning": null,
            "Oracle VM": null,
            "Vector NTI": null,
            "VDSL": null,
            "Nutrition": null,
            "Blood Typing": null,
            "Nastran": null,
            "Mobile TV": null,
            "First Year Experience": null,
            "Korean Culture": null,
            "TSS": null,
            "Ultrasound Therapy": null,
            "Foreign Policy": null,
            "Downstream Oil &amp; Gas": null,
            "RSA Ace Server": null,
            "jBase": null,
            "Electricity": null,
            "RSoft": null,
            "SAP SD": null,
            "HSPA": null,
            "Physics": null,
            "DBAccess": null,
            "Variance Analysis": null,
            "Diagnostic Ultrasound": null,
            "RCA": null,
            "Financial Planning": null,
            "Global Mobility": null,
            "HVAC": null,
            "Medicine": null,
            "Youth Outreach": null,
            "Karl Fisher": null,
            "PTC Creo": null,
            "Keyboardist": null,
            "WSH": null,
            "RHEV": null,
            "IKB": null,
            "Yields": null,
            "New Product Ideas": null,
            "ODE": null,
            "PVR": null,
            "White Box Testing": null,
            "Ulead VideoStudio": null,
            "CSA 2010": null,
            "Oil Paint": null,
            "Government Contracting": null,
            "Working With Children": null,
            "CCIP": null,
            "Microsoft Dynamics GP": null,
            "Chemical Engineering": null,
            "MySQL Cluster": null,
            "EOD": null,
            "Firewalls": null,
            "Classical Guitar": null,
            "Gmail": null,
            "Trials": null,
            "Curating": null,
            "CDMA": null,
            "XOG": null,
            "Zend Framework": null,
            "Eggs": null,
            "Store Management": null,
            "Kaspersky Antivirus": null,
            "Therapists": null,
            "OMT": null,
            "DDI": null,
            "Kantar": null,
            "VSAM": null,
            "VSAM": null,
            "Komodo": null,
            "JUnit": null,
            "IAR": null,
            "White Papers": null,
            "Managed Services": null,
            "VXI": null,
            "IACUC": null,
            "Computer Games": null,
            "ASIC": null,
            "BMP": null,
            "Electronic Warfare": null,
            "Applied Behavior Analysis": null,
            "MMIC": null,
            "GSLC": null,
            "MDL": null,
            "Rhinoplasty": null,
            "CD Mastering": null,
            "Music Festivals": null,
            "WSS 2.0": null,
            "IGOR Pro": null,
            "PPE": null,
            "Military Training": null,
            "OMA": null,
            "Technical Support": null,
            "VB.NET": null,
            "Music Production": null,
            "MDB": null,
            "Performance Appraisal": null,
            "global HCM": null,
            "HMDA": null,
            "UHF": null,
            "SLC500": null,
            "MPLS-TP": null,
            "Media Planning": null,
            "Operational Risk": null,
            "E-Learning": null,
            "MQC": null,
            "SSH": null,
            "Usability Engineering": null,
            "Machine Tools": null,
            "Simulations": null,
            "NDDS": null,
            "Node.js": null,
            "HP Blade": null,
            "Mental Health": null,
            "OEMs": null,
            "UV/Vis": null,
            "NCDA": null,
            "Sales Presentations": null,
            "SQL*Plus": null,
            "Creative Direction": null,
            "DNS Management": null,
            "European Politics": null,
            "HSPA": null,
            "GFSI": null,
            "Theory": null,
            "Training": null,
            "Omega": null,
            "Two-phase Flow": null,
            "MHE": null,
            "Aspen HYSYS": null,
            "VTP": null,
            "Hodes IQ": null,
            "HQL": null,
            "Bylaws": null,
            "Legal Writing": null,
            "Waterfall": null,
            "solid-state NMR": null,
            "White Box Testing": null,
            "RSA SecurID": null,
            "FBCB2": null,
            "TMDLs": null,
            "Gemba Kaizen": null,
            "Windows Vista": null,
            "DV Cleared": null,
            "VDSL": null,
            "Oxidation": null,
            "Requirements Analysis": null,
            "Guerrilla Marketing": null,
            "Working at Height": null,
            "CGEIT": null,
            "Human Computer Interaction": null,
            "Overall Wellness": null,
            "Onshore": null,
            "Whole Life": null,
            "IT Transformation": null,
            "LLVM": null,
            "Multilingual": null,
            "Dyeing": null,
            "Oligonucleotide Synthesis": null,
            "Warranty": null,
            "ABAP-OO": null,
            "TI DSPs": null,
            "DNA Repair": null,
            "XML Schema": null,
            "MMIS": null,
            "Overhaul": null,
            "SAP PP": null,
            "Strategic Planning": null,
            "Urban Redevelopment": null,
            "SMO": null,
            "Legal Advice": null,
            "Routing Protocols": null,
            "NQA-1": null,
            "EWB": null,
            "ICD-9-CM": null,
            "Azerbaijani": null,
            "Switchboard Operator": null,
            "Applicant Tracking Systems": null,
            "Running": null,
            "PTP": null,
            "Rural Marketing": null,
            "MySQL": null,
            "DVD Architect": null,
            "Business Transformation": null,
            "CWNA": null,
            "Kyoto Protocol": null,
            "VDA": null,
            "VTS": null,
            "Zoology": null,
            "CBD": null,
            "QPST": null,
            "Year-end Close": null,
            "Move Up Buyers": null,
            "Basel II": null,
            "Hotels": null,
            "Trade Marketing": null,
            "Vulcan": null,
            "Bluetooth": null,
            "Korean Culture": null,
            "OMAP": null,
            "Talent Acquisition": null,
            "Offshore Outsourcing": null,
            "Vehicle Dynamics": null,
            "nCode": null,
            "OBIEE": null,
            "Multi-Unit": null,
            "Aerial Photography": null,
            "Process Simulation": null,
            "RRC": null,
            "Short Sales": null,
            "Java": null,
            "RCA": null,
            "Drums": null,
            "VB.NET": null,
            "ICT Governance": null,
            "Karate": null,
            "PKI": null,
            "TIG Welding": null,
            "SNMP": null,
            "Leadership Development": null,
            "QR": null,
            "HTC": null,
            "JDF": null,
            "CMDB": null,
            "Atomic Absorption": null,
            "MCS": null,
            "FDA GMP": null,
            "RPG Free": null,
            "SDSF": null,
            "Xpress": null,
            "Control Systems Design": null,
            "FX Swaps": null,
            "Nielsen Data": null,
            "VCI": null,
            "SBRT": null,
            "Creative Non-fiction": null,
            "HR Metrics": null,
            "UK GAAP": null,
            "Audio Engineering": null,
            "Smart Metering": null,
            "CSS Sprites": null,
            "Festivals": null,
            "NVU": null,
            "Apache Pig": null,
            "Essbase": null,
            "Time Management": null,
            "Commercial Real Estate": null,
            "Bathrooms": null,
            "Payroll Taxes": null,
            "PMO": null,
            "Book Illustration": null,
            "XForms": null,
            "MBE": null,
            "DNA Sequencing": null,
            "NDC": null,
            "DTDs": null,
            "High Sense Of Urgency": null,
            "Product Management": null,
            "HNI": null,
            "Visual SVN": null,
            "Databases": null,
            "Educational Outreach": null,
            "Customer Retention": null,
            "Sheet Metal": null,
            "Xactly": null,
            "RUP": null,
            "UDS": null,
            "JSF": null,
            "Cell Biology": null,
            "Retail Banking": null,
            "Valuation": null,
            "iReport": null,
            "Grocery": null,
            "MW": null,
            "UDP": null,
            "PMO Design": null,
            "Mysis": null,
            "Banking": null,
            "Media TV": null,
            "Xsigo": null,
            "Management by Objectives": null,
            "ArcGIS": null,
            "Pdf": null,
            "PTFE": null,
            "SSAS 2008": null,
            "Qmail": null,
            "Sniffer": null,
            "Board Development": null,
            "VLC": null,
            "XATA": null,
            "Geological Mapping": null,
            "Integrated Circuit Design": null,
            "CGI/Perl": null,
            "Xcart": null,
            "UK Employment Law": null,
            "Wiring": null,
            "Rsync": null,
            "RBI": null,
            "Zeolites": null,
            "ETABS": null,
            "Business Ethics": null,
            "IVF": null,
            "DDD": null,
            "Value Engineering": null,
            "RPO": null,
            "Interactive TV": null,
            "Web Development": null,
            "Historical Research": null,
            "Bodywork": null,
            "XTRACT": null,
            "TSP": null,
            "Sanction II": null,
            "Food Industry": null,
            "Japanese Business Culture": null,
            "jQuery Mobile": null,
            "Oracle Identity Manager": null,
            "Employee Benefits": null,
            "Lotus Domino": null,
            "FDDI": null,
            "Market Knowledge": null,
            "Hotel Management": null,
            "BWA": null,
            "Cash Handling": null,
            "Secure FTP": null,
            "Sensory Evaluation": null,
            "Snoring": null,
            "JBA": null,
            "RTC": null,
            "Design Thinking": null,
            "Azerbaijani": null,
            "BMC Patrol": null,
            "Criminal Justice": null,
            "Genomics": null,
            "Kaizen Leadership": null,
            "TMN": null,
            "Value Engineering": null,
            "Patient Advocacy": null,
            "Embedded C": null,
            "DUI Defense": null,
            "JDBC": null,
            "RIP": null,
            "Amazon VPC": null,
            "Kyoto Protocol": null,
            "DDL": null,
            "GAAP": null,
            "Gaming Industry": null,
            "BPF": null,
            "Krakatoa": null,
            "Airline Ticketing": null,
            "Key Account Development": null,
            "Transportation Management": null,
            "3Com NBX": null,
            "Organizational Effectiveness": null,
            "Jigs": null,
            "CFII": null,
            "TMDLs": null,
            "Tenacious Work Ethic": null,
            "Visual Arts": null,
            "Machine Tools": null,
            "Humanitarian": null,
            "Oil Changes": null,
            "Corporate Branding": null,
            "TMON": null,
            "Apollo GDS": null,
            "DDE": null,
            "Mixed-use": null,
            "IATSE": null,
            "Guest Lecturing": null,
            "IPSec": null,
            "Rehabilitation Psychology": null,
            "Canon XH-A1": null,
            "Quality Auditing": null,
            "Sybase SQL Anywhere": null,
            "Facilities Management": null,
            "Switching": null,
            "SFR": null,
            "MCS": null,
            "Media Relations": null,
            "Time &amp; Attendance": null,
            "Retail Sales": null,
            "Analytical Ultracentrifugation": null,
            "Slogans": null,
            "International Human Rights": null,
            "Sports Play-by-play": null,
            "Bootstrap": null,
            "Onboarding": null,
            "VDSL2": null,
            "Microsoft Word": null,
            "Natural Gas": null,
            "Zooarchaeology": null,
            "NDT": null,
            "EPR": null,
            "Forecasting": null,
            "Whole Life": null,
            "Tires": null,
            "TSYS": null,
            "AHU": null,
            "Public Relations": null,
            "Corporate Governance": null,
            "Eye Exams": null,
            "Eye Treatments": null,
            "PVSyst": null,
            "Aircraft": null,
            "UV Mapping": null,
            "HP Data Protector": null,
            "SNOMED": null,
            "DLC": null,
            "Geological Mapping": null,
            "Gynecology": null,
            "Sustainable Development": null,
            "Force Protection": null,
            "Climate Change": null,
            "JDE One World": null,
            "Manufacturing": null,
            "Waxing": null,
            "IFC": null,
            "UDF": null,
            "Adult Education": null,
            "Humanitarian Assistance": null,
            "MBAL": null,
            "JIRA": null,
            "Umbrellas": null,
            "PDM Works": null,
            "Organization Skills": null,
            "User Interface Design": null,
            "Voice Over": null,
            "Linux Kernel": null,
            "Kindergarten": null,
            "Hypertension": null,
            "Djbdns": null,
            "Aerial Photography": null,
            "Corporate Identity": null,
            "Watercolor Illustration": null,
            "Medication Therapy Management": null,
            "XAML": null,
            "Aerial Silks": null,
            "AQTESOLV": null,
            "Kickstart": null,
            "CPLD": null,
            "ASME": null,
            "Grassroots": null,
            "Cost Efficiency": null,
            "GSD": null,
            "Banking": null,
            "nCloth": null,
            "Wide Format Printing": null,
            "Gift Cards": null,
            "DGA": null,
            "Embedded C": null,
            "FTO": null,
            "Partnership Taxation": null,
            "SDLC": null,
            "SAP MM Module": null,
            "Statistics": null,
            "QAC": null,
            "Utilization Review": null,
            "Gymnastics": null,
            "RHEL": null,
            "VPM": null,
            "International Economics": null,
            "RSView": null,
            "Kaseya": null,
            "Fraud": null,
            "TDMA": null,
            "GBA": null,
            "Key Person Insurance": null,
            "IxChariot": null,
            "DHCP": null,
            "DLNA": null,
            "Quantitative Finance": null,
            "Life Cycle Assessment": null,
            "UCINET": null,
            "Social Media Blogging": null,
            "DC Circuits": null,
            "CSV": null,
            "RTB": null,
            "Agents": null,
            "Cloud Computing IaaS": null,
            "Cfengine": null,
            "C-TPAT": null,
            "Roofers": null,
            "Planning": null,
            "Secretarial Skills": null,
            "Typewriter": null,
            "Kronos WFC": null,
            "Functional Specifications": null,
            "Franchising": null,
            "Ocean Transportation": null,
            "JScript": null,
            "CBEST": null,
            "IFS": null,
            "Usability": null,
            "Digital Video": null,
            "PTS": null,
            "eGRC": null,
            "XForms": null,
            "Irrigation": null,
            "FX Trading": null,
            "MDI": null,
            "Gynecology": null,
            "Konica": null,
            "Bathrooms": null,
            "OLAP": null,
            "LDOM": null,
            "FI-AA": null,
            "Lotus Notes": null,
            "Visual Identity Design": null,
            "iReport": null,
            "FTP": null,
            "Outerwear": null,
            "KXEN": null,
            "VPM": null,
            "PC Anywhere": null,
            "JTIDS": null,
            "Kickstart": null,
            "MBCI": null,
            "SNF": null,
            "WMS Implementations": null,
            "American English": null,
            "AWS CWI": null,
            "Microsoft Word": null,
            "Film Production": null,
            "Space Planning": null,
            "QADirector": null,
            "Urban Agriculture": null,
            "ICU": null,
            "Digital Signage": null,
            "WSAD": null,
            "DxDesigner": null,
            "WPF": null,
            "Eblasts": null,
            "Fashion Illustration": null,
            "EFTPOS": null,
            "Gigabit Ethernet": null,
            "Functional Specifications": null,
            "CNN Newsource": null,
            "PMBOK": null,
            "HP Servers": null,
            "RC Detailing": null,
            "OMAP": null,
            "Science": null,
            "Aerobics": null,
            "Process Optimization": null,
            "MDS": null,
            "Documentaries": null,
            "Focus Groups": null,
            "Qlogic": null,
            "Entrust PKI": null,
            "Awk": null,
            "American Literature": null,
            "Yachting": null,
            "Private Piloting": null,
            "Switches": null,
            "Product Life Cycle": null,
            "EOI": null,
            "Rule Of Law": null,
            "Furnishings": null,
            "Medical Devices": null,
            "Museums": null,
            "OEMs": null,
            "XML Standards": null,
            "UDS": null,
            "MXG": null,
            "LSS": null,
            "Risk Analysis": null,
            "Zend": null,
            "cDNA": null,
            "Job Analysis": null,
            "Glaucoma": null,
            "Cement": null,
            "Direct Sales": null,
            "Piping": null,
            "Microsoft Dynamics NAV": null,
            "Twitter": null,
            "Music Theory": null,
            "Microsoft Dynamics ERP": null,
            "RPC": null,
            "Wellness": null,
            "DTMF": null,
            "Beauty Industry": null,
            "LDPC": null,
            "PC building": null,
            "Funding": null,
            "NICET": null,
            "LDAP Administration": null,
            "EPA": null,
            "Tier II Reporting": null,
            "Youth Development": null,
            "Ehcache": null,
            "Sales Tax": null,
            "RF Circuits": null,
            "Reactive Ion Etching": null,
            "vBlock": null,
            "GSA Schedule": null,
            "Organizational Development": null,
            "Uzbek": null,
            "Audio Engineering": null,
            "Microsoft Dynamics ERP": null,
            "DC Circuits": null,
            "FDMA": null,
            "Single Family Homes": null,
            "SQL*Plus": null,
            "Compensation &amp; Benefits": null,
            "KPI Implementation": null,
            "QoS": null,
            "JDK": null,
            "Underscore.js": null,
            "Yoga": null,
            "FTSE 100": null,
            "DNA quantification": null,
            "HBA": null,
            "Social TV": null,
            "After FX": null,
            "BWA": null,
            "FP-C": null,
            "Title Insurance": null,
            "DTT": null,
            "Apache ZooKeeper": null,
            "JAX-WS": null,
            "SGE": null,
            "NRP Instruction": null,
            "Annual Giving": null,
            "Urinalysis": null,
            "GNU/Linux": null,
            "Combined Cycle": null,
            "DMT": null,
            "WSPG": null,
            "Cross Functional Team Building": null,
            "Aerial Lifts": null,
            "NRF": null,
            "Shipping": null,
            "Fine Art Photography": null,
            "Feature Writing": null,
            "OEM negotiations": null,
            "Media Relations": null,
            "MC2": null,
            "XFP": null,
            "Ableton Live": null,
            "TTL": null,
            "CDM": null,
            "BBx": null,
            "Pyrotechnics": null,
            "Illustration": null,
            "Site Development": null,
            "Hair Care": null,
            "LPIC": null,
            "IVA": null,
            "VPLS": null,
            "Young People": null,
            "JD Edwards": null,
            "Oracle RDC": null,
            "NCAA Compliance": null,
            "IHE": null,
            "HTML Emails": null,
            "DQL": null,
            "American English": null,
            "Security Clearance": null,
            "NFS": null,
            "Duty Drawback": null,
            "Pharmacy Benefit Management": null,
            "Mortgage Banking": null,
            "Community Development": null,
            "RTF": null,
            "CTA": null,
            "ICH-GCP": null,
            "Smarty": null,
            "Software Project Management": null,
            "Xbox": null,
            "Fundraising": null,
            "EIFS": null,
            "HP Procurve Networking": null,
            "Western Blotting": null,
            "TI DSPs": null,
            "TM1": null,
            "PTFE": null,
            "GFAAS": null,
            "PSpice": null,
            "Aircraft Systems": null,
            "VMware VTSP": null,
            "Thin Films": null,
            "MLOAD": null,
            "VSAT": null,
            "VTP": null,
            "Substance Abuse Prevention": null,
            "Uzbek": null,
            "NVivo": null,
            "Juvederm": null,
            "Demand Generation": null,
            "WHMIS": null,
            "CPCU": null,
            "iSCSI": null,
            "OLEDs": null,
            "Piano Playing": null,
            "OOH": null,
            "Avid Newscutter": null,
            "Affordable Housing": null,
            "Jimmy Jib": null,
            "Ocular Disease": null,
            "ICD-9": null,
            "Citrix": null,
            "Oracle E-Business Suite": null,
            "IFC": null,
            "PPMS": null,
            "Value Stream Mapping": null,
            "Klarity": null,
            "KRA": null,
            "UCINET": null,
            "UDP": null,
            "Hudson": null,
            "FTP": null,
            "TSCM": null,
            "Oracle RDC": null,
            "Human Resource Development": null,
            "Pneumatic Tools": null,
            "PDF Creator": null,
            "Key Performance Indicators": null,
            "PMP": null,
            "VTC": null,
            "NS2": null,
            "SWOT analysis": null,
            "Microsoft Publisher": null,
            "Web Services": null,
            "PMO set-up": null,
            "PowerPoint": null,
            "Industrial Ethernet": null,
            "European History": null,
            "Radio Production": null,
            "MMO": null,
            "UCC filings": null,
            "Algorithms": null,
            "Koi Ponds": null,
            "dSPACE": null,
            "WPS": null,
            "Hypertension": null,
            "Broadband": null,
            "Value Stream Mapping": null,
            "Organizational Effectiveness": null,
            "BMC Remedy AR System": null,
            "PGP": null,
            "Norwegian": null,
            "Single Family Homes": null,
            "Joint Ventures": null,
            "CDPE Designation": null,
            "DCP": null,
            "Axioma": null,
            "UK GAAP": null,
            "HBOC": null,
            "vBlock": null,
            "MRV": null,
            "GNU Make": null,
            "MBTI": null,
            "DMRB": null,
            "Zinc": null,
            "Human Computer Interaction": null,
            "QlikView": null,
            "RSLinx": null,
            "Snacks": null,
            "Work Effectively": null,
            "UNIX Utilities": null,
            "Keyboardist": null,
            "Game Development": null,
            "Instructional Design": null,
            "Xytech": null,
            "RSView": null,
            "OSI Model": null,
            "Custom Furniture": null,
            "Konica": null,
            "IES VE": null,
            "LEED AP": null,
            "Alarm Systems": null,
            "JSA": null,
            "Eyewear": null,
            "Two-factor Authentication": null,
            "UCINET": null,
            "Applied Kinesiology": null,
            "NCP": null,
            "Business Analysis": null,
            "Brand Ambassadorship": null,
            "Architectural Illustration": null,
            "FCAW": null,
            "FEED": null,
            "Jets": null,
            "Client Services": null,
            "SAP OM": null,
            "PL/SQL": null,
            "EBIT": null,
            "Kaledo": null,
            "JavaBeans": null,
            "Urban Planning": null,
            "RBD": null,
            "Social Justice": null,
            "Lyra": null,
            "Award Ceremonies": null,
            "DVD Replication": null,
            "Omron": null,
            "IGRP": null,
            "WSIB Claims Management": null,
            "MFS": null,
            "VPM": null,
            "CSS Sprites": null,
            "Abstract Paintings": null,
            "FTTx": null,
            "GDP": null,
            "PFlow": null,
            "AHA": null,
            "Tablet PC": null,
            "Journalism": null,
            "TPE": null,
            "CgFX": null,
            "Web Content Management": null,
            "Medical Imaging": null,
            "UltraTax CS": null,
            "CMYK": null,
            "Embedded Systems": null,
            "NICE Call Recording": null,
            "EOB": null,
            "International Relations": null,
            "Black &amp; White Photography": null,
            "IBM XIV": null,
            "BPML": null,
            "Long-term Care": null,
            "Fire Alarm": null,
            "NCIC": null,
            "LVM": null,
            "KOL Management": null,
            "Outdoor Education": null,
            "iPod": null,
            "MDS 3.0": null,
            "CNN Newsource": null,
            "CBI": null,
            "Politics": null,
            "Financial Audits": null,
            "Thermal Oxidizers": null,
            "Payroll Taxes": null,
            "Air Compressors": null,
            "Vlookup": null,
            "VMware VTSP": null,
            "JAX-WS": null,
            "CSCS": null,
            "PDS": null,
            "LTO": null,
            "Employee Training": null,
            "HSE Management Systems": null,
            "MS Excel Pivot Tables": null,
            "Due Diligence": null,
            "PVD": null,
            "LAN-WAN": null,
            "Laboratory Skills": null,
            "iReport": null,
            "Sh": null,
            "Tcpdump": null,
            "ISO 13485": null,
            "SI": null,
            "DFA": null,
            "Software Design": null,
            "Zymography": null,
            "Programming": null,
            "TCA": null,
            "NTFS": null,
            "CgFX": null,
            "Commercial Litigation": null,
            "RTO": null,
            "Writing": null,
            "Organizational Behavior": null,
            "Feature Articles": null,
            "TM1": null,
            "Foreign Policy": null,
            "OGC Gateway Reviews": null,
            "Public Speaking": null,
            "For Sale By Owner": null,
            "Alternative Medicine": null,
            "Djbdns": null,
            "CNAS": null,
            "OLEDB": null,
            "FxCop": null,
            "DXX": null,
            "AWS CWI": null,
            "RFC": null,
            "Equity Trading": null,
            "Amazon RDS": null,
            "DFT": null,
            "VSD": null,
            "Operating Room": null,
            "Xalan": null,
            "Direct Sales": null,
            "Xsigo": null,
            "Linux KVM": null,
            "Usability Testing": null,
            "NBFC": null,
            "10 Key": null,
            "Zoom": null,
            "Ministry Of Defence": null,
            "Lesson Planning": null,
            "Snow Leopard": null,
            "Xoops": null,
            "Job Search": null,
            "Oracle XE": null,
            "Wicklander-Zulawski Interview &amp; Interrogation": null,
            "Combined Cycle": null,
            "Environmental Science": null,
            "Citrix XenDesktop": null,
            "Visual Arts": null,
            "Book Reviews": null,
            "Major Gift Development": null,
            "Healthcare Consulting": null,
            "DCF": null,
            "Radio": null,
            "Arbitration": null,
            "FGD": null,
            "Machine Tools": null,
            "VFX Supervision": null,
            "Hospitality Management": null,
            "CSA 2010": null,
            "Fiction Writing": null,
            "EEO Investigations": null,
            "Big 4": null,
            "Pyrometallurgy": null,
            "MBOX": null,
            "Black &amp; White": null,
            "Capacity Utilization": null,
            "Film": null,
            "RMI": null
        }});
        console.log(`plugin initialize`)
    }

    render(){        

        return (
            <form className="col s12">
                <div className="row" style={{display: 'flex'}}>
                    <div className="input-field col s6 searchcont" style={{margin: '0 auto'}}>
                        <input placeholder="Enter text here to search" id="search" type="text" className="validate" style={{
                            borderRadius: '4px',
                            border: '1px solid #ccc',
                            paddingLeft: '10px',
                        }}/>
                        <button className="btn" style={{minHeight: '82%', position:'absolute', top:0, right:0, bottom: 0}}><i className="material-icons">search</i></button>
                    </div>
                </div>
            </form>
        )
    } 
}